version: '2'

services:
  postgres:
    restart: always
    image: postgres
    environment:
      POSTGRES_USER: kidc
      POSTGRES_PASSWORD: postGresKidcPas4Login2plus2Production
    ports:
      - '5432:5432'
    volumes:
      - 'postgres:/var/lib/postgresql/data'
  redis:
    image: 'redis:3.2-alpine'
    command: redis-server --requirepass redisRuns4Fun
    ports:
      - '6379:6379'
    volumes:
      - 'redis:/var/lib/redis/data'

  app:
    depends_on:
      - 'postgres'
      - 'redis'
    build: .
    ports:
      - '80:3000'
    env_file:
      - '.env.prod'

  sidekiq:
    depends_on:
      - 'postgres'
      - 'redis'
    build: .
    command: sidekiq -C config/sidekiq.yml.erb
    volumes:
      - '.:/kidc'
    env_file:
      - '.env.prod'

  cable:
    depends_on:
      - 'redis'
    build: .
    command: puma -p 28080 cable/config.ru
    ports:
      - '28080:28080'
    volumes:
      - '.:/kidc'
    env_file:
      - '.env.prod'

volumes:
  redis:
  postgres:
