version: '2'

services:
  postgres:
    restart: always
    image: postgres
    environment:
      POSTGRES_USER: kidc
      POSTGRES_PASSWORD: kidc
    ports:
      - '5432:5432'
    volumes:
      - 'postgres:/var/lib/postgresql/data'
  redis:
    image: 'redis:3.2-alpine'
    command: redis-server --requirepass redisRuns4Fun
    ports:
      - '6379:6379'
    volumes:
      - 'redis:/var/lib/redis/data'
  app:
    stdin_open: true
    tty: true
    depends_on:
      - 'postgres'
      - 'redis'
    build: .
    ports:
      - '3000:3000'
    volumes:
      - '.:/kidc'
    volumes_from:
      - box
    env_file:
      - '.env'

#  sidekiq:
#    depends_on:
#      - 'postgres'
#      - 'redis'
#    build: .
#    command: cp /usr/local/bundle/Gemfile.lock $INSTALL_PATH/ && sidekiq -C config/sidekiq.yml.erb
#    volumes:
#      - '.:/kidc'
#    volumes_from:
#      - box
#    env_file:
#      - '.env'
#
#  cable:
#    depends_on:
#      - 'redis'
#    build: .
#    command: cp /usr/local/bundle/Gemfile.lock $INSTALL_PATH/ && puma -p 28080 cable/config.ru
#    ports:
#      - '28080:28080'
#    volumes:
#      - '.:/kidc'
#    volumes_from:
#      - box
#    env_file:
#      - '.env'
  box:
    image: busybox
    volumes:
      - /box

volumes:
  redis:
  postgres:
